all:
  hosts:
    master1:
      ansible_host: 3.87.159.233
    worker1:
      ansible_host: 3.90.107.239
    worker2:
      ansible_host: 3.237.185.16
  children:
    masters:
      hosts:
        master1:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: k8s-cluster-key
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    workers:
      hosts:
        worker1:
        worker2:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: k8s-cluster-key
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

